# Generated by Django 5.1.6 on 2025-10-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiosdiagnosticos',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='estudiosdiagnosticos',
            name='especialidad',
            field=models.ManyToManyField(related_name='EspecialidadesDelEstudio', to='hospital_personal.especialidades'),
        ),
    ]
