# Generated by Django 5.1.6 on 2025-10-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuario', '0001_initial'),
        ('hospital_personal', '0002_remove_estudiosdiagnosticos_especialidad_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usuarioxespecialidadxservicioxrolesprofesionales',
            constraint=models.UniqueConstraint(fields=('usuario', 'rol_profesional'), name='unique_usuario_rol_profesional'),
        ),
    ]
