# Generated by Django 5.1.6 on 2025-10-15 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuario', '0002_rolesprofesionales_especialidad_and_more'),
        ('hospital_personal', '0003_usuarioxespecialidadxservicioxrolesprofesionales_unique_usuario_rol_profesional'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioRolProfesionalAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlUsuario.rolesprofesionales')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidadesUsuario', to='controlUsuario.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='UsuarioXEspecialidadXServicioXrolesProfesionales',
        ),
        migrations.AddConstraint(
            model_name='usuariorolprofesionalasignado',
            constraint=models.UniqueConstraint(fields=('usuario', 'rol_profesional'), name='unique_usuario_rol_profesional'),
        ),
    ]
