# Generated by Django 5.1.6 on 2025-10-17 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuario', '0002_rolesprofesionales_especialidad_and_more'),
        ('hospital_personal', '0004_usuariorolprofesionalasignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_personal.departamento'),
        ),
        migrations.CreateModel(
            name='UsuarioLugarTrabajoAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_personal.jorna_laboral')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_personal.lugar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlUsuario.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='UsuarioXDepartamentoXJornadaXLugar',
        ),
        migrations.AddConstraint(
            model_name='usuariolugartrabajoasignado',
            constraint=models.UniqueConstraint(fields=('usuario', 'jornada'), name='unique_usuario_jornada'),
        ),
    ]
