# Generated by Django 5.1.6 on 2025-10-18 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuario', '0002_rolesprofesionales_especialidad_and_more'),
        ('hospital_personal', '0005_lugar_departamento_usuariolugartrabajoasignado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariolugartrabajoasignado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuariosAsignadosAEsteLugar', to='controlUsuario.usuario'),
        ),
    ]
