# Generated by Django 5.1.6 on 2025-10-15 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlUsuario', '0001_initial'),
        ('hospital_personal', '0003_usuarioxespecialidadxservicioxrolesprofesionales_unique_usuario_rol_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesprofesionales',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_personal.especialidades'),
        ),
        migrations.AddField(
            model_name='rolesprofesionales',
            name='servicio_diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital_personal.serviciodiagnostico'),
        ),
    ]
